#!/bin/bash

red="\033[31m"
green="\033[32m"
yellow="\033[33m"
reset="\033[0m"

function usage () {
	echo "Usage: $0 [options]"
	echo "Options:"
	echo "        -d, --device <DEVICE>    The serial port"
}

VALID_ARGS=$(getopt -o d:h --long device:,help -- "$@")
eval set -- "$VALID_ARGS"

while :
do
	case "$1" in
		-d | --device)
		       	device="$2"
		       	shift 2 ;;
		-h | --help)
			usage
			exit 0
			;;
		--)
			shift
		       	break ;;
		*)
		       	echo "Unexpected option: $1"; exit 1 ;;
	esac
done

if [ -z "$device" ]
then
	echo "Please provide the serial port" >&2
	exit 1
fi

TERM_ARGS=()
# Disable flow control RTS/CTS
TERM_ARGS+=(-crtscts)
# Disable modem signals, DCD (Data Carrier Detect) line
TERM_ARGS+=(clocal)
# Disable software flow control XON/XOFF
TERM_ARGS+=(-ixon)
TERM_ARGS+=(-ixoff)
# Disable postprocess output
TERM_ARGS+=(-opost)
# Since esp-idf monitor change the min to 0 (non-blocking mode)
TERM_ARGS+=(min 1)

stty -F $device 115200 ${TERM_ARGS[@]} -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke

cleanup() {
	echo "kill $cat_pid"
	kill $cat_pid
}

trap cleanup EXIT

#cat $device &
cat $device > >( sed $'s/.*/\033[32m&\033[0m/' ) &
cat_pid=$!
while read line; do
       	#echo "send: $line" >&2
	echo "$line" > $device
done
